import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AdminSidebar from "./AdminSidebar";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const cookie = await cookies().get("accessToken")
  if(!cookie){
    redirect("/")
  }
  return <SidebarProvider className={'flex'}>
    <AdminSidebar/>
    <SidebarTrigger/>
    {children}
  </SidebarProvider>;
}
