export const PERMISSIONS = {
  USER: {
    LOGOUT: "USER.LOGOUT",
    UPDATE: "USER.UPDATE",
    CHANGE_PASSWORD:"USER.CHANGE_PASSWORD",
  },
  BLOG:{
    CREATE:"BLOG.CREATE",
    UPDATE:"BLOG.UPDATE",
    DELETE:"BLOG.DELETE",
  },
  ADMIN:{
    DELETE_BLOG:"ADMIN.DELETE_BLOG",
    DELETE_USER:"ADMIN.DELETE_USER",
    BAN_USER:"ADMIN.BAN_USER",
    ADD_PERMISSION_TO_USER:"ADMIN.ADD_PERMISSION_TO_USER",
    ADD_PERMISSION_TO_ROLE:"ADMIN.ADD_PERMISSION_TO_ROLE",
    DELETE_PERMISSION_FROM_USER:"ADMIN.DELETE_PERMISSION_FROM_USER",
    DELETE_PERMISSION_FROM_ROLE:"ADMIN.DELETE_PERMISSION_FROM_ROLE",
    ADD_ROLE_TO_USER:"ADMIN.ADD_ROLE_TO_USER",
    DELETE_ROLE_FROM_USER:"ADMIN.DELETE_ROLE_FROM_USER",
    CREATE_ROLE:"ADMIN.CREATE_ROLE",
  }
};
